name: template
description: A Flutter MVVM template project with BLoC, Retrofit and Hive.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Routing
  go_router: ^10.0.0
  
  # Networking
  dio: ^5.3.2
  retrofit: ^4.0.1
  connectivity_plus: ^4.0.2
  json_annotation: ^4.9.0
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Localization
  easy_localization: ^3.0.3
  
  # Others
  get_it: ^7.6.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  mockito: ^5.4.2
  build_runner: ^2.4.6
  retrofit_generator: ^7.0.8
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  bloc_test: ^9.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
