name: Setup SonarScanner
description: Download and install SonarScanner CLI based on OS, architecture, and version

inputs:
  os:
    description: Target OS (linux, macos, windows)
    required: false
    default: ubuntu-latest

  arch:
    description: CPU architecture (x64, aarch64)
    required: false
    default: x64

  version:
    description: SonarScanner version (e.g., 7.1.0.4889)
    required: false
    default: 7.1.0.4889

runs:
  using: composite
  steps:
    - name: Setup and Install SonarScanner
      shell: bash
      run: |
        set -euo pipefail

        OS="${{ inputs.os }}"
        ARCH="${{ inputs.arch }}"
        VERSION="${{ inputs.version }}"
        EXT="zip"

        echo "Detected OS: $OS"
        echo "Detected ARCH: $ARCH"
        echo "SonarScanner Version: $VERSION"

        # Normalize OS names
        if [[ "$OS" == "ubuntu-latest" ]]; then
          PLATFORM="linux"
        elif [[ "$OS" == "windows-latest" ]]; then
          PLATFORM="windows"
        elif [[ "$OS" == "macos-latest" ]]; then
          PLATFORM="macosx"
        else
          echo "Unsupported OS: $OS"
          exit 1
        fi

        # Determine architecture suffix
        ARCH_SUFFIX="-x64"
        if [[ "$ARCH" == "aarch64" ]]; then
          ARCH_SUFFIX="-aarch64"
        fi

        # Download SonarScanner
        FILE_NAME="sonar-scanner-cli-${VERSION}-${PLATFORM}${ARCH_SUFFIX}.${EXT}"
        DOWNLOAD_URL="https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/${FILE_NAME}"

        echo "Downloading from: $DOWNLOAD_URL"
        curl -fsSL -o sonar-scanner.${EXT} "$DOWNLOAD_URL"

        # Extract
        INSTALL_DIR="$GITHUB_WORKSPACE/sonar-scanner"
        mkdir -p "$INSTALL_DIR"
        unzip -q sonar-scanner.${EXT} -d "$INSTALL_DIR"

        # Set PATH for next steps
        SCANNER_BIN_DIR=$(find "$INSTALL_DIR" -type d -name "bin" | head -n 1)
        echo "Adding $SCANNER_BIN_DIR to PATH"
        echo "$SCANNER_BIN_DIR" >> "$GITHUB_PATH"

    - name: Verify SonarScanner Installation
      shell: bash
      run: |
        echo "SonarScanner Version Installed:"
        sonar-scanner --version
