name: 'Setup SonarScanner'
description: 'Downloads and installs SonarScanner CLI'
inputs:
  os:
    description: 'Operating system (linux, macos, windows)'
    required: true
    type: string
    default: 'linux'
    options:
      - 'linux'
      - 'macos'
      - 'windows'
  version:
    description: 'SonarScanner version (e.g., 7.1.0.4889)'
    required: true
    type: string
    default: 7.1.0.4889
  arch:
    description: 'CPU architecture (x64, arm64, aarch64)'
    required: false
    default: 'x64'
    type: string
    options:
      - 'x64'
      - 'arm64'
      - 'aarch64'
runs:
  using: 'composite'
  steps:
    - name: Determine SonarScanner URL and Filename
      id: set_sonarscanner_url
      shell: bash
      run: |
        OS="${{ inputs.os }}"
        VERSION="${{ inputs.version }}"
        ARCH="${{ inputs.arch }}"
        EXTENSION="zip"

        if [ "$OS" == "linux" ]; then
          PLATFORM="linux"
          if [ "$ARCH" == "aarch64" ]; then
            ARCHITECTURE="-aarch64"
          else
            ARCHITECTURE="-x64"
          fi
        elif [ "$OS" == "macos" ]; then
          PLATFORM="macosx"
          ARCHITECTURE="-x64" #only x64 for macos
        elif [ "$OS" == "windows" ]; then
          PLATFORM="windows"
          ARCHITECTURE="-x64"
        fi

        FILE_NAME="sonar-scanner-cli-${VERSION}-${PLATFORM}${ARCHITECTURE}.${EXTENSION}"
        DOWNLOAD_URL="https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/${FILE_NAME}"

        echo "DOWNLOAD_URL=$DOWNLOAD_URL" >> $GITHUB_OUTPUT
        echo "FILE_NAME=$FILE_NAME" >> $GITHUB_OUTPUT
        echo "INSTALL_DIR=/opt/sonar-scanner-${VERSION}" >> $GITHUB_OUTPUT #default
        if [ "$OS" == "windows" ]; then
          echo "INSTALL_DIR=C:\\sonar-scanner-${VERSION}" >> $GITHUB_OUTPUT
        fi
    - name: Download SonarScanner
      shell: bash
      run: |
        echo "Downloading SonarScanner from ${{ steps.set_sonarscanner_url.outputs.DOWNLOAD_URL }}"
        curl -L -o "${{ steps.set_sonarscanner_url.outputs.FILE_NAME }}"
    - name: Extract SonarScanner
      shell: bash
      run: |
        OS="${{ inputs.os }}"
        FILE_NAME="${{ steps.set_sonarscanner_url.outputs.FILE_NAME }}"
        INSTALL_DIR="${{ steps.set_sonarscanner_url.outputs.INSTALL_DIR }}"
        echo "Extracting SonarScanner to $INSTALL_DIR"
        mkdir -p "$INSTALL_DIR"
        if [ "$OS" == "windows" ]; then
          powershell -Command "Expand-Archive -Path '$FILE_NAME' -DestinationPath '$INSTALL_DIR'"
        else
          unzip -q "$FILE_NAME" -d "$INSTALL_DIR"
        fi
    - name: Add SonarScanner to PATH
      shell: bash
      run: |
        OS="${{ inputs.os }}"
        INSTALL_DIR="${{ steps.set_sonarscanner_url.outputs.INSTALL_DIR }}"
        echo "Adding SonarScanner to PATH"
        if [ "$OS" == "windows" ]; then
          echo "::add-path::$INSTALL_DIR"
        else
          echo "export PATH=$PATH:$INSTALL_DIR/sonar-scanner-${{ inputs.version }}/bin" >> $GITHUB_PATH
        fi
    - name: Verify SonarScanner Installation
      shell: bash
      run: |
        echo "Verifying SonarScanner installation..."
        sonar-scanner -h

