name: Setup SonarScanner
description: Download and install SonarScanner CLI based on OS, arch, and version

inputs:
  os:
    description: Target OS (linux, macos, windows)
    required: false
    default: linux

  arch:
    description: CPU architecture (x64, arm64, aarch64)
    required: false
    default: x64

  version:
    description: SonarScanner version (e.g., 5.0.1.3006)
    required: false
    default: 5.0.1.3006

runs:
  using: composite
  steps:
    - name: Generate, download, and extract SonarScanner
      shell: bash
      run: |
        OS="${{ inputs.os }}"
        ARCH="${{ inputs.arch }}"
        VERSION="${{ inputs.version }}"
        EXT="zip"

        # Set platform and architecture suffix
        if [[ "$OS" == "linux" ]]; then
          PLATFORM="linux"
          ARCH_SUFFIX="-x64"
          if [[ "$ARCH" == "aarch64" ]]; then
            ARCH_SUFFIX="-aarch64"
          fi
        elif [[ "$OS" == "macos" ]]; then
          PLATFORM="macosx"
          ARCH_SUFFIX="-x64"
        elif [[ "$OS" == "windows" ]]; then
          PLATFORM="windows"
          ARCH_SUFFIX="-x64"
        else
          echo "Unsupported OS: $OS"
          exit 1
        fi

        FILE_NAME="sonar-scanner-cli-${VERSION}-${PLATFORM}${ARCH_SUFFIX}.${EXT}"
        DOWNLOAD_URL="https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/${FILE_NAME}"

        echo "Downloading SonarScanner from $DOWNLOAD_URL"
        curl -L -o sonar-scanner.${EXT} "$DOWNLOAD_URL"

        echo "Extracting SonarScanner..."
        INSTALL_DIR="$GITHUB_WORKSPACE/sonar-scanner"
        mkdir -p "$INSTALL_DIR"

        if [[ "$OS" == "windows" ]]; then
          unzip -q sonar-scanner.zip -d "$INSTALL_DIR"
        else
          unzip -q sonar-scanner.zip -d "$INSTALL_DIR"
        fi

        echo "$INSTALL_DIR/sonar-scanner-${VERSION}/bin" >> $GITHUB_PATH

    - name: Verify SonarScanner installation
      shell: bash
      run: sonar-scanner --version
