name: Build Flutter App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Flutter App for All Platforms
    runs-on: ${{ matrix.runner }}
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: android
            runner: ubuntu-latest
          - platform: linux
            runner: ubuntu-latest
          - platform: windows
            runner: windows-latest
          - platform: macos
            runner: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Set Build Number
        run: echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Enable Desktop (if needed)
        if: matrix.platform != 'android'
        run: flutter config --enable-${{ matrix.platform }}-desktop

      - name: Build Application
        run: |
          if [ "${{ matrix.platform }}" = "android" ]; then
            flutter build apk --release --build-name=1.0.${{ env.BUILD_NUMBER }}
          else
            flutter build ${{ matrix.platform }} --release --build-name=1.0.${{ env.BUILD_NUMBER }}
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}-build-${{ env.BUILD_NUMBER }}
          path: |
            ${{ format('build/{0}/', matrix.platform) }}
            ${{ matrix.platform == 'android' && 'build/app/outputs/flutter-apk/app-release.apk' || '' }}
          if-no-files-found: warn