name: v1 - Install Flutter on All OS

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  install-flutter:
    name: Setup Flutter on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x64] # Extend later with arm64 if needed
        include:
          - os: macos-latest
            arch: arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: ./.github/actions/setup/flutter
        with:
          os: ${{ matrix.os == 'ubuntu-latest' && 'linux' || matrix.os == 'windows-latest' && 'windows' || 'macos' }}
          arch: ${{ matrix.arch }}
          version: 3.32.0-0.2.pre
          is-beta: true

      - name: Show Flutter Version
        run: flutter --version

      - name: Run Flutter Doctor
        run: flutter doctor -v
