name: v1 - Install Flutter on All OS

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  install-flutter:
    name: Setup Flutter & Build ${{ matrix.target }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        # arch: [x64]
        # target: [apk, windows, linux, macos, ios]

        include:
          - os: macos-latest
            arch: arm64
            target: ios

          - os: windows-latest
            arch: x64
            target: windows

          - os: ubuntu-latest
            arch: x64
            target: apk

          - os: ubuntu-latest
            arch: x64
            target: linux

          - os: macos-latest
            arch: x64
            target: macos

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: ./.github/actions/setup/flutter
        with:
          os: ${{ matrix.os == 'ubuntu-latest' && 'linux' || matrix.os == 'windows-latest' && 'windows' || 'macos' }}
          arch: ${{ matrix.arch }}
          version: 3.32.0-0.2.pre
          is-beta: true

      - name: Show Flutter Version
        run: flutter --version

      - name: Run Flutter Doctor
        run: flutter doctor -v

      - name: Build Flutter Target
        run: |
          case "${{ matrix.target }}" in
            apk)
              flutter build apk --release
              ;;
            ios)
              flutter build ios --release
              ;;
            macos)
              flutter build macos --release
              ;;
            windows)
              flutter build windows --release
              ;;
            linux)
              flutter build linux --release
              ;;
            *)
              echo "Unknown build target: ${{ matrix.target }}"
              exit 1
              ;;
          esac
